---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ubuntu1404
    image: ubuntu:14.04

provisioner:
  name: ansible
  options:
    v: true
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: goss
  enabled: false
