---
- name: Converge
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Install python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false
    - name: Gather facts
      setup:

  roles:
    - role: ansible-container-role-upstart
